dont auto clone getting-started, bad logic pollutes remote environments

diff --git a/libexec/_ao b/libexec/_ao
--- a/libexec/_ao
+++ b/libexec/_ao
@@ -33,36 +33,13 @@ function enforce_rvm {
   exec $pth_ruby_loader $ruby_deploy "$0" "$@"
 }
 
-FLAGS_proxy_default="$FLAGS_FALSE"
-if [[ ! -d "$(ryaml $shome/config/deploy.yml chef_path)" ]]; then
-  FLAGS_proxy_default="$FLAGS_TRUE"
-  export _AO_CHEF="$HOME/.getting-started"
-fi
-
-if [[ "$FLAGS_proxy_default" = "$FLAGS_TRUE" ]]; then
-  if [[ ! -d "$HOME/.getting-started" ]]; then
-    git clone git@github.com:zendesk/getting-started "$HOME/.getting-started"
-    pushd $HOME/.getting-started > /dev/null
-    bin/pancake update
-    popd > /dev/null
-  else
-    pushd $HOME/.getting-started > /dev/null
-    if [[ "$(cat .counter 2>&-)" < "$(cat $shome/.counter 2>&-)" ]]; then
-      bin/pancake update
-    fi
-    popd > /dev/null
-  fi
-
-  get_started
-fi
-
 enforce_rvm "$@"
 
 # define command line options:
 #   var name, default, description, short option
 DEFINE_string "gateway" "" "deploy gateway host" "G"
 DEFINE_boolean "autoconf" "$FLAGS_TRUE" "use config/ssh to configure remote access" "z"
-DEFINE_boolean "proxy" "$FLAGS_proxy_default" "use a gateway to proxy deploys" "p"
+DEFINE_boolean "proxy" "$FLAGS_FALSE" "use a gateway to proxy deploys" "p"
 DEFINE_boolean "direct" "$FLAGS_FALSE" "override proxy" "d"
 DEFINE_string "chef" "" "location to chef repo with opsdb" "c"
 DEFINE_string "tag" "HEAD" "tag to deploy in production" "t"
@@ -172,39 +149,36 @@ function main {
 
         bundle check 2>&1 >/dev/null || { bundle install --quiet --local --path vendor/bundle || bundle check > /dev/null; }
         aomain "$nm_component" "$@"
-        exit
-      fi
-     
-      if [[ "$#" > 0 ]]; then
-        case "$1" in
-          all|world)
-            logger_fatal "cannot use all or world, these are dangerous"
-            exit 1
-            ;;
-          production)
-            if [[ -z "$FLAGS_tag" || "$FLAGS_tag" = "HEAD" ]]; then
-              case "$(deploy_basename $0)" in
-                hosts|debug)
-                  true
-                  ;;
-                *)
-                  logger_fatal "must specify a version using --tag"
-                  exit 1
-                  ;;
-              esac
-            fi
-            ;;
-        esac
-      fi
+      else 
+        if [[ "$#" > 0 ]]; then
+          case "$1" in
+            all|world)
+              logger_fatal "cannot use all or world, these are dangerous"
+              exit 1
+              ;;
+            production)
+              if [[ -z "$FLAGS_tag" || "$FLAGS_tag" = "HEAD" ]]; then
+                case "$(deploy_basename $0)" in
+                  hosts|debug)
+                    true
+                    ;;
+                  *)
+                    logger_fatal "must specify a version using --tag"
+                    exit 1
+                    ;;
+                esac
+              fi
+              ;;
+          esac
+        fi
 
-      local gateway="$FLAGS_gateway"
-      if [[ -n "$FLAGS_ssh_login" ]]; then
-        gateway="${FLAGS_ssh_login}@${gateway}"
-      fi
+        local gateway="$FLAGS_gateway"
+        if [[ -n "$FLAGS_ssh_login" ]]; then
+          gateway="${FLAGS_ssh_login}@${gateway}"
+        fi
 
-      exec $shome/sbin/proxy "$FLAGS_gateway" "$FLAGS_tag" $(deploy_basename $0) "$nm_component" "$@"
-      logger_fatal "could not run the proxy command, this is an esoteric error"
-      exit 1
+        $shome/sbin/proxy "$FLAGS_gateway" "$FLAGS_tag" $(deploy_basename $0) "$nm_component" "$@"
+      fi
       ;;
   esac
 }
