merge version_file and version_tag

diff --git a/libexec/deploy b/libexec/deploy
--- a/libexec/deploy
+++ b/libexec/deploy
@@ -1,63 +1,29 @@
 #!/bin/bash -e
 
-function bump_version_file {
-  case "$1" in
-    patch|minor|major)
-      bump=$1; shift
-      set $(cat VERSION | sed 's#\.# #g')
-      case "$bump" in
-        patch)
-          echo "$1.$2.$(($3 + 1))"
-          ;;
-        minor)
-          echo "$1.$(($2 + 1)).0"
-          ;;
-        major)
-          echo "$(($1 + 1)).0.0"
-          ;;
-      esac > VERSION
-      ;;
-    *)
-      ver_new=$1; shift
-      set $(echo "$ver_new" | sed 's#\.# #g') 0
-      M=$1; shift
-      m=$1; shift
-      p=$1; shift
+function bump_version {
+  ensure_clean_git_status
 
-      tmp_version=$(mktemp -t XXXXXXXXX)
-      (echo "$(($M+0)).$(($m+0)).$(($p+0))" > $tmp_version) 2>&-
-      ver_new_same=$(cat $tmp_version)
-      rm -f $tmp_version
-
-      if [[ $ver_new = $ver_new_same ]]; then
-        echo "$ver_new" > VERSION
-      else
-        echo "ERROR: invalid version: $ver_new" 1>&2
-        exit 1
-      fi
-      ;;
-  esac
-
-  if [[ -f Gemfile ]]; then
-    bundle check 2>&1 >/dev/null || { bundle --quiet install --local --path vendor/bundle || bundle check > /dev/null; }
-    git add Gemfile.lock
+  local_file=
+  if [[ -f VERSION || -L VERSION ]]; then
+    if [[ -e VERSION ]]; then
+      local_file=1
+    else
+      echo "ERROR: cannot write to VERSION file" 1>&2
+      exit 1
+    fi
   fi
 
-  git add VERSION
-
-  ver_bumped=$(cat VERSION)
-  git commit -m "bump: $ver_bumped"
-  git_tag "v$ver_bumped"
-  git push
-  echo $ver_bumped
-}
-
-function bump_version_tag {
   tmp_version=$(mktemp -t XXXXXXXXX)
+  if [[ -n $local_file ]]; then
+    cp VERSION $tmp_version
+  else
+    git tag | perl -ne 'm{^v(\d+)\.(\d+)\.(\d+)$} && printf("v%03d.%03d.%03d v%d.%d.%d\n",$1,$2,$3,$1,$2,$3)' | sort -r | head -1 | awk '{print $2}' > $tmp_version
+  fi
+
   case "$1" in
     patch|minor|major)
       bump=$1; shift
-      set $(cat tmp_version| sed 's#\.# #g')
+      set $(cat $tmp_version | sed 's#\.# #g')
       case "$bump" in
         patch)
           echo "$1.$2.$(($3 + 1))"
@@ -77,14 +43,10 @@ function bump_version_tag {
       m=$1; shift
       p=$1; shift
 
-      tmp_version=$(mktemp -t XXXXXXXXX)
       (echo "$(($M+0)).$(($m+0)).$(($p+0))" > $tmp_version) 2>&-
       ver_new_same=$(cat $tmp_version)
-      rm -f $tmp_version
 
-      if [[ $ver_new = $ver_new_same ]]; then
-        echo "$ver_new" > $tmp_version
-      else
+      if [[ $ver_new != $ver_new_same ]]; then
         echo "ERROR: invalid version: $ver_new" 1>&2
         exit 1
       fi
@@ -92,6 +54,21 @@ function bump_version_tag {
   esac
 
   ver_bumped=$(cat $tmp_version)
+  rm -f $tmp_version
+  ensure_git_tag_available "v$ver_bumped"
+
+  if [[ -n $local_file ]]; then
+    echo $ver_bumped > VERSION
+    git add VERSION
+    if [[ -f Gemfile ]]; then
+      bundle check 2>&1 >/dev/null || { bundle --quiet install --local --path vendor/bundle || bundle check > /dev/null; }
+      git add Gemfile.lock
+    fi
+
+    git commit -m "bump: $ver_bumped"
+    git push
+  fi
+
   git_tag "v$ver_bumped"
   echo $ver_bumped
 }
@@ -204,17 +181,7 @@ case "$(basename $0)" in
         ;;
 
       bump)
-        ensure_clean_git_status
-        if [[ -f VERSION || -L VERSION ]]; then
-          if [[ -e VERSION ]]; then
-            bump_version_file "$@"
-          else
-            echo "ERROR: cannot write to VERSION file" 1>&2
-            exit 1
-          fi
-        else
-          bump_version_tag
-        fi
+        bump_version "$@"
         ;;
 
       *)
